// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: common/proto/profile_service/profile_service.proto

package prof

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profuser *ProfUser `protobuf:"bytes,1,opt,name=profuser,proto3" json:"profuser,omitempty"`
}

func (x *CreateNewUser) Reset() {
	*x = CreateNewUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewUser) ProtoMessage() {}

func (x *CreateNewUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewUser.ProtoReflect.Descriptor instead.
func (*CreateNewUser) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewUser) GetProfuser() *ProfUser {
	if x != nil {
		return x.Profuser
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{1}
}

type GetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profuser []*ProfUser `protobuf:"bytes,1,rep,name=profuser,proto3" json:"profuser,omitempty"`
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetProfuser() []*ProfUser {
	if x != nil {
		return x.Profuser
	}
	return nil
}

type ProfUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Name           string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname        string         `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Password       string         `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email          string         `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Telephone      string         `protobuf:"bytes,6,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Gender         string         `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate      string         `protobuf:"bytes,8,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Biography      string         `protobuf:"bytes,9,opt,name=biography,proto3" json:"biography,omitempty"`
	Experiences    []*Experiences `protobuf:"bytes,10,rep,name=experiences,proto3" json:"experiences,omitempty"`
	Educations     []*Educations  `protobuf:"bytes,11,rep,name=educations,proto3" json:"educations,omitempty"`
	Skills         []*Skills      `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	Followers      []*Followers   `protobuf:"bytes,13,rep,name=followers,proto3" json:"followers,omitempty"`
	Followings     []*Followings  `protobuf:"bytes,14,rep,name=followings,proto3" json:"followings,omitempty"`
	Ispublic       bool           `protobuf:"varint,15,opt,name=ispublic,proto3" json:"ispublic,omitempty"`
	FollowRequests []string       `protobuf:"bytes,16,rep,name=followRequests,proto3" json:"followRequests,omitempty"`
}

func (x *ProfUser) Reset() {
	*x = ProfUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfUser) ProtoMessage() {}

func (x *ProfUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfUser.ProtoReflect.Descriptor instead.
func (*ProfUser) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProfUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfUser) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *ProfUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProfUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfUser) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *ProfUser) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ProfUser) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ProfUser) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *ProfUser) GetExperiences() []*Experiences {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *ProfUser) GetEducations() []*Educations {
	if x != nil {
		return x.Educations
	}
	return nil
}

func (x *ProfUser) GetSkills() []*Skills {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ProfUser) GetFollowers() []*Followers {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *ProfUser) GetFollowings() []*Followings {
	if x != nil {
		return x.Followings
	}
	return nil
}

func (x *ProfUser) GetIspublic() bool {
	if x != nil {
		return x.Ispublic
	}
	return false
}

func (x *ProfUser) GetFollowRequests() []string {
	if x != nil {
		return x.FollowRequests
	}
	return nil
}

type Experiences struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Experience string `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
}

func (x *Experiences) Reset() {
	*x = Experiences{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Experiences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experiences) ProtoMessage() {}

func (x *Experiences) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experiences.ProtoReflect.Descriptor instead.
func (*Experiences) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{4}
}

func (x *Experiences) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

type Educations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Educations string `protobuf:"bytes,1,opt,name=educations,proto3" json:"educations,omitempty"`
}

func (x *Educations) Reset() {
	*x = Educations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Educations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Educations) ProtoMessage() {}

func (x *Educations) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Educations.ProtoReflect.Descriptor instead.
func (*Educations) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{5}
}

func (x *Educations) GetEducations() string {
	if x != nil {
		return x.Educations
	}
	return ""
}

type Skills struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skills string `protobuf:"bytes,1,opt,name=skills,proto3" json:"skills,omitempty"`
}

func (x *Skills) Reset() {
	*x = Skills{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skills) ProtoMessage() {}

func (x *Skills) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skills.ProtoReflect.Descriptor instead.
func (*Skills) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{6}
}

func (x *Skills) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

type Followers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Followers string `protobuf:"bytes,1,opt,name=followers,proto3" json:"followers,omitempty"`
}

func (x *Followers) Reset() {
	*x = Followers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Followers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Followers) ProtoMessage() {}

func (x *Followers) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Followers.ProtoReflect.Descriptor instead.
func (*Followers) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{7}
}

func (x *Followers) GetFollowers() string {
	if x != nil {
		return x.Followers
	}
	return ""
}

type Followings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Followings string `protobuf:"bytes,1,opt,name=followings,proto3" json:"followings,omitempty"`
}

func (x *Followings) Reset() {
	*x = Followings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Followings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Followings) ProtoMessage() {}

func (x *Followings) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_profile_service_profile_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Followings.ProtoReflect.Descriptor instead.
func (*Followings) Descriptor() ([]byte, []int) {
	return file_common_proto_profile_service_profile_service_proto_rawDescGZIP(), []int{8}
}

func (x *Followings) GetFollowings() string {
	if x != nil {
		return x.Followings
	}
	return ""
}

var File_common_proto_profile_service_profile_service_proto protoreflect.FileDescriptor

var file_common_proto_profile_service_profile_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x66, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x66, 0x75, 0x73, 0x65, 0x72, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66,
	0x75, 0x73, 0x65, 0x72, 0x22, 0xaa, 0x04, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x79, 0x12,
	0x33, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x65, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73,
	0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x2d, 0x0a, 0x09,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73,
	0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x22, 0x2d, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x2c, 0x0a, 0x0a, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x20,
	0x0a, 0x06, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73,
	0x22, 0x29, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x22, 0x2c, 0x0a, 0x0a, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x32, 0xf9, 0x01, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x50, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77,
	0x55, 0x73, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x22, 0x06, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x3a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x22, 0x18, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x12, 0x1a, 0x06, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x3a, 0x08, 0x70, 0x72, 0x6f,
	0x66, 0x75, 0x73, 0x65, 0x72, 0x42, 0x46, 0x5a, 0x44, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x57, 0x53, 0x2d,
	0x42, 0x53, 0x2d, 0x45, 0x50, 0x2d, 0x54, 0x49, 0x4d, 0x32, 0x2d, 0x32, 0x30, 0x32, 0x32, 0x2f,
	0x78, 0x77, 0x73, 0x62, 0x73, 0x2d, 0x65, 0x70, 0x74, 0x69, 0x6d, 0x36, 0x2d, 0x32, 0x30, 0x32,
	0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_profile_service_profile_service_proto_rawDescOnce sync.Once
	file_common_proto_profile_service_profile_service_proto_rawDescData = file_common_proto_profile_service_profile_service_proto_rawDesc
)

func file_common_proto_profile_service_profile_service_proto_rawDescGZIP() []byte {
	file_common_proto_profile_service_profile_service_proto_rawDescOnce.Do(func() {
		file_common_proto_profile_service_profile_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_profile_service_profile_service_proto_rawDescData)
	})
	return file_common_proto_profile_service_profile_service_proto_rawDescData
}

var file_common_proto_profile_service_profile_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_proto_profile_service_profile_service_proto_goTypes = []interface{}{
	(*CreateNewUser)(nil),  // 0: auth.CreateNewUser
	(*GetAllRequest)(nil),  // 1: auth.GetAllRequest
	(*GetAllResponse)(nil), // 2: auth.GetAllResponse
	(*ProfUser)(nil),       // 3: auth.ProfUser
	(*Experiences)(nil),    // 4: auth.Experiences
	(*Educations)(nil),     // 5: auth.Educations
	(*Skills)(nil),         // 6: auth.Skills
	(*Followers)(nil),      // 7: auth.Followers
	(*Followings)(nil),     // 8: auth.Followings
}
var file_common_proto_profile_service_profile_service_proto_depIdxs = []int32{
	3,  // 0: auth.CreateNewUser.profuser:type_name -> auth.ProfUser
	3,  // 1: auth.GetAllResponse.profuser:type_name -> auth.ProfUser
	4,  // 2: auth.ProfUser.experiences:type_name -> auth.Experiences
	5,  // 3: auth.ProfUser.educations:type_name -> auth.Educations
	6,  // 4: auth.ProfUser.skills:type_name -> auth.Skills
	7,  // 5: auth.ProfUser.followers:type_name -> auth.Followers
	8,  // 6: auth.ProfUser.followings:type_name -> auth.Followings
	1,  // 7: auth.ProfileService.GetAll:input_type -> auth.GetAllRequest
	0,  // 8: auth.ProfileService.AddNewUser:input_type -> auth.CreateNewUser
	0,  // 9: auth.ProfileService.UpdateUser:input_type -> auth.CreateNewUser
	2,  // 10: auth.ProfileService.GetAll:output_type -> auth.GetAllResponse
	0,  // 11: auth.ProfileService.AddNewUser:output_type -> auth.CreateNewUser
	0,  // 12: auth.ProfileService.UpdateUser:output_type -> auth.CreateNewUser
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_common_proto_profile_service_profile_service_proto_init() }
func file_common_proto_profile_service_profile_service_proto_init() {
	if File_common_proto_profile_service_profile_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_profile_service_profile_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Experiences); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Educations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skills); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Followers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_profile_service_profile_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Followings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_profile_service_profile_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_profile_service_profile_service_proto_goTypes,
		DependencyIndexes: file_common_proto_profile_service_profile_service_proto_depIdxs,
		MessageInfos:      file_common_proto_profile_service_profile_service_proto_msgTypes,
	}.Build()
	File_common_proto_profile_service_profile_service_proto = out.File
	file_common_proto_profile_service_profile_service_proto_rawDesc = nil
	file_common_proto_profile_service_profile_service_proto_goTypes = nil
	file_common_proto_profile_service_profile_service_proto_depIdxs = nil
}
